# Generated by Django 5.0.3 on 2024-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('onboard_frequency', models.IntegerField()),
                ('offboard_frequency', models.IntegerField()),
            ],
        ),
    ]
