# Generated by Django 5.0.3 on 2024-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('station_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('onboard_frequency', models.IntegerField()),
                ('offboard_frequency', models.IntegerField()),
            ],
        ),
    ]
